language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: vTFEgx9DxlcGYQ2ROD8Ltesgeuk5T8gnUjZm1kqZHkYyLJRJ1p5uXz9lfCRFxp2+AxA0mzuMxYN5Sp/qqvtlElR8gIqPRXqbookxH17oxWlC6WLvsJ5YhwkjCa+j3VCD3603ra09F6QTF4x3B2h2oDBOJ2qa+CU8N7TxHokdaYAKvIOW2qRl8w/iCvNmRIKBfAyWf1LcrguatJwcJVz0hG1+8jqkzf8Fe4jebtRc2PIvxduuFu8yIcO4ttToqpistrx2vjH6h7X6Mr6AjIZLUjXEfyH/ktEZK0rIkDRYIVwJEqqqgqZIvRPomUKo1njWkrxWS6xaHJ3vml9g8u4pyOv5VUFIZC0XA8U1tQqTxdnpPKtFYf081XdC2dH2i2T+ChZjTa3Yr+AsbnTXFUEmtlBYY0hxXB8OJ90BybKnhHrRlENtKJkMK4CA0UshJht+jvzxPOuxnoxd6dMBIH08985p5Eh5ekrJipAQbwoVlQmABGQySs8Jql2Wtt/PjUJsfZKbnDQqstbhfEfGEZCKuJtGcIBrhpEIvXRaajakbiWUERBU1RETG/FxjqJbaGQmogOc9gBPZiGzZ0Ug7IAsds4wyeMTZn1MS6s7vNpbI9htT8f4Z5257mQa//iQ1eVTAESZ5Dbli2N/4/KH3t0FBmtKwz5kDmeRRhXE7y8xZ7E=
  file:
    - 'ccount.js'
    - 'ccount.min.js'
  on:
    tags: true
