language: node_js
node_js:
- '4.0'
- '8.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: yMdEfjIxa7pOa1ufZdvKew03nD9JWHIOGC8fWAIsoYx22/cjLWWJMY9p1AOilPt4hMlZBbuSdsUWUuXrV3shTjdLNeQk/DqfEe2+hTAtOFYEnnanaA1ybSreVNjby0BFmHCZoJ6j/ICgvGfiCyHgrQfRR4ubQWGQW9cKmur0Ze/Wn4NYE2ULnCyJgbph9rJ8wkCLTnKo94FkaOF9H78Eslv/6XytojhLdoYyhK1zto33EKA7Sohugajk5BOeORihxbqFuz7THO/ASQkGYedeZRU+LoBEKcqXhuJIn9xUB/gRR+GQqODtTm2LnDyteSMs9WaoSp3aeCIaM3mpiE281sfas4Pi/VAI47T7OCbvp6S1Okx437zilknOiW9Sdwu9m1OSjTulEHCRz7aztjmVOXCqOAIUPXfxHaXwGsvOVPYh6PjX92kQGd3c8F2fXwiFU1S2TTTubDoa7kc9Ipoo5ulHpQ036FfZujlDNcCoqJHQCqXTUvw5WCeq89EM2sm+6rWnoriWULGRNh0gR/L7iuL0Dt+Lost+LVHldzDdf4NZAM7R5QkfVMrie6QHBzrNAHzDWdt2D3GjNJI/yy+XlK7UL2m5mUzbk+B7dJvBWoPNs0nCfO5ohdCt8CHiKhvVUtQQvCkb3nbMLTeKsC4xwqEVdg862KPpsrB4tp/WpnA=
  file:
    - "ccount.js"
    - "ccount.min.js"
  on:
    tags: true
    node: '8.0'
